server:
  port: 9090

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: admin
      username: admin-user
      password: admin-password

mongock:
  change-logs-scan-package: mu.mongock.demo.changelog


